# frozen_string_literal: true

source 'https://rubygems.org'

gem 'importmap-rails'
gem 'pathogen_view_components', path: '..'
gem 'propshaft'
gem 'puma', '>= 5.0'
gem 'rails', '~> 8.1.1'
gem 'rails_icons'
gem 'tailwindcss-rails'

gem 'tzinfo-data', platforms: %i[windows jruby]

group :development do
  gem 'debug', platforms: %i[mri windows], require: 'debug/prelude'
  gem 'lookbook'
end
